# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Steven Speicher
tagline:          'Front End Developer'
description:      'web dev at <a target="_blank" href="http://uw.edu">UW</a>, previously in Nebraska on <a target="_blank" href="http://www.plattebasintimelapse.com">PBT</a>'
url:              http://www.stvnspchr.com
baseurl:          /
assets: 		  http://assets.stvnspchr.com/img/

author:
  name:           'Steven Speicher'
  url:            https://twitter.com/stvnspchr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/stvnspchr
