# Setup
title:            Steven Speicher
tagline:          'Software Engineer'
description:      'Front End Engineer at <a target="_blank" href="http://seattletimes.com">Seattle Times</a>'
url:              http://www.stvnspchr.com
baseurl:          /
assets: 		  http://assets.stvnspchr.com/img/

author:
  name:           'Steven Speicher'
  url:            https://twitter.com/stvnspchr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/stvnspchr
