# Permalinks
permalink:        pretty

# Setup
title:            Steven Speicher
tagline:          'Front End Developer'
description:      'Front End Dev at <a target="_blank" href="http://uw.edu">University of Washington</a>'
url:              http://www.stvnspchr.com
baseurl:          /
assets: 		  http://assets.stvnspchr.com/img/

author:
  name:           'Steven Speicher'
  url:            https://twitter.com/stvnspchr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/stvnspchr
