# Setup
title: Steven Speicher
tagline: 'Software Engineer'
description: 'Software Engineer at The New York Times'
url: http://www.stvnspchr.com
assets: http://assets.stvnspchr.com/img/

author:
  name: 'Steven Speicher'
  url: https://twitter.com/stvnspchr

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/stvnspchr
