# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Steven Speicher
tagline:          'Web Producer'
description:      'A site about me'
url:              http://www.stvnspchr.com
baseurl:          /
assets: 		  http://assets.stvnspchr.com/img/

author:
  name:           'Steven Speicher'
  url:            https://twitter.com/stvnspchr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/stvnspchr
